#!/usr/bin/env bash
# Install nginx and echo "Holberton School"
# per main file example


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
