#!/usr/bin/env bash
# Installing HAProxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

strF="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_backend\n\n" 
strB="\nbackend custom_backend\n\tbalance roundrobin\n\tserver web01 18.208.140.32:80 check\n\tserver web02 100.26.28.99:80 check\n"

sudo echo -e $strF | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo -e $strB | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart