#!/usr/bin/env bash
# display numbers 1-100
# display FizzBuzz when * of 3 and 5
# display Fizz when *3
# display Buzz when *5
# display # otherwise
# list format
x=0

while [ $((x++)) -le 99 ]

do
    if ! ((x%15))
    then
        echo "FizzBuzz"
    
    elif ! ((x%3))
    then
        echo "Fizz"

    elif ! ((x%5))
    then
        echo "Buzz"
        
    else
        echo "$x"
fi
done
