#!/usr/bin/env bash
# display Holberton School 10x but 9th say Hi NewLine
# use while
# use if
x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x == 9 ]
    then
        echo "Hi"
    fi
    ((x++))
done
