#!/usr/bin/env bash
# display cont of CD
# display in list format
# display Where only the part of the name after the first dash is
# Use for loop
# no hidden files

for x in *

do 
    echo "$x" | cut -d "-" -f 2
done
