#!/usr/bin/env bash
# receive information about the holbertonschool files
# must use if and else, no case
# if exist print holbertonschool file exist
# if not exist print holbertonschool file does not exist
# if files exist print if empty, not empty, or not a reg file

x="holbertonschool"

if [ ! -e $x ]
then
    echo "$x file does not exist"
    
    else
        echo "$x file exists"

if [ ! -s $x ]
then
    echo "$x file is empty"

    else
        echo "$x file is not empty"

    fi

if [ -f $x ]
then
    echo "$x is a regular file"

fi
fi
