#!/usr/bin/env bash
#create RSA Key Pair
#Name of the created private key must be holberton
#Number of bits in the created key to be created 4096
#The created key must be protected by the passphrase betty

ssh-keygen -f holberton -b 4096 -N betty

#using ManPage -f file name -b bits -n passphrase